### ISSUE TITLE
Update Setup for new driver names

### ISSUE THREAD

**Issue by jts93** [simplic-systems/simplic-cdn-odbc#23]
The driver and the DLLs were renamed in order to reflect the difference between x86 and x64 versions. The setup needs to be updated with the correct names. See the attached files for an example registry configuration.

[odbcinst32_release.reg.txt](https://github.com/simplic-systems/simplic-cdn-odbc/files/683317/odbcinst32_release.reg.txt)
[odbcinst64_release.reg.txt](https://github.com/simplic-systems/simplic-cdn-odbc/files/683316/odbcinst64_release.reg.txt)

**Comment by simplicbe** [comment]
Done
